// The four files a crawler and a link unfurler read straight off disk, none of them
// rendered by Angular. og.png and logo-512.png are pixels; robots.txt and llms.txt are
// plain text `Seo`/`structured-data.ts` and `postbuild.ts` point at.
//
// llms.txt is the one exception to "reads public/ verbatim" (R408): every PAGE_META
// description carries a contract-derived price (R49), so the file is generated by
// `writeLlmsTxt` in postbuild on every build rather than committed. Its test therefore
// reads the built tree, the same way `head-tags.spec.ts` reads what the render wrote.
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import { PAGE_META, SITE_URL } from '../../src/app/lib/page-meta'
import { PUBLIC_DIR } from '../../scripts/postbuild'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const pub = (f: string) => resolve(packageRoot, 'public', f)
const dist = (f: string) => resolve(packageRoot, PUBLIC_DIR, f)

const pngSize = (f: string) => {
  const b = readFileSync(f)
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20), bytes: b.length }
}

/**
 * RFC 9309's resolution rule, and deliberately *only* that much of it (R409): the longest
 * matching `Allow`/`Disallow` prefix wins, plain string prefix, no `$` or `*` extension. The
 * first fix here used `Disallow: /dev$`, a Google/Bing-only end anchor -- under a parser that
 * treats `$` as a literal character (the strict reading of the base RFC), that rule matches no
 * real path at all, so the bare `/dev` route would not be blocked by *any* line, which is the
 * same shape of silent failure R409 already cost once. This resolver supports nothing beyond
 * the base spec on purpose, so a file that only passes because of an extension fails here
 * rather than only failing in front of a stricter crawler. Reimplemented rather than imported,
 * for the same reason as before: the point is to prove the *file* resolves correctly, not to
 * trust a copy of the algorithm that could drift from what a crawler does.
 */
function robotsAllows(lines: string[], path: string): boolean {
  const rules = lines
    .map((l) => /^(Allow|Disallow):\s*(\S*)\s*$/.exec(l))
    .filter((m): m is RegExpExecArray => m !== null)
    .map((m) => ({ allow: m[1] === 'Allow', rule: m[2]! }))
  let best: { allow: boolean; rule: string } | null = null
  for (const r of rules) {
    if (path.startsWith(r.rule) && (!best || r.rule.length > best.rule.length)) best = r
  }
  return best ? best.allow : true
}

describe('public files', () => {
  it('og.png is 1200x630 and small enough to be fetched by every link unfurler', () => {
    const s = pngSize(pub('og.png'))
    expect([s.w, s.h]).toEqual([1200, 630])
    expect(s.bytes).toBeLessThan(300_000)
  })

  it('logo-512.png is square and at least the 112px Google asks of an Organization logo', () => {
    const s = pngSize(pub('logo-512.png'))
    expect(s.w).toBe(s.h)
    expect(s.w).toBeGreaterThanOrEqual(112)
  })

  it('robots.txt keeps crawlers out of the private areas and names the sitemap', () => {
    const lines = readFileSync(pub('robots.txt'), 'utf8').split(/\r?\n/)
    for (const p of ['/app', '/admin', '/api']) expect(lines).toContain(`Disallow: ${p}`)
    expect(lines).toContain(`Sitemap: ${SITE_URL}/sitemap.xml`)
    expect(lines).not.toContain('Disallow: /')
  })

  /**
   * The channel this bug actually travels on: not the text of the file, but how a real parser
   * resolves it. REP (as Google, Bing and the `robots-parser` package Lighthouse's
   * `is-crawlable` audit uses all implement it) picks the *longest matching prefix rule*, not
   * the first one written -- so a plain `Disallow: /dev` also matches `/developers`, because
   * `'/developers'.startsWith('/dev')`. *Captured*: Lighthouse failed `/developers`'s SEO
   * category at 69/100 with "Page is blocked from indexing", naming line 4 of this exact file,
   * on the one page spec section 7's launch outreach points at (R409).
   *
   * Checked against `robotsAllows`'s plain-RFC-9309 resolution, not an extended one: the fix is
   * `Disallow: /dev` plus a more specific `Allow: /developers` (11 characters beats 4), which
   * needs no `$`/`*` support to resolve correctly (R409 fix round 1) -- unlike the first
   * attempt, which anchored `/dev` with `$` and silently stopped blocking the bare `/dev` route
   * under a parser that does not extend the base spec.
   */
  it('does not shadow a public route by prefix (Disallow: /dev must not also block /developers)', () => {
    const lines = readFileSync(pub('robots.txt'), 'utf8').split(/\r?\n/)
    for (const route of Object.keys(PAGE_META)) expect(robotsAllows(lines, route), route).toBe(true)
    for (const blocked of ['/dev', '/dev/earnings', '/app', '/admin', '/api']) {
      expect(robotsAllows(lines, blocked), blocked).toBe(false)
    }
  })

  it('llms.txt names every public route', () => {
    const t = readFileSync(dist('llms.txt'), 'utf8')
    for (const route of Object.keys(PAGE_META)) expect(t).toContain(`${SITE_URL}${route === '/' ? '/' : route}`)
  })
})
